# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "533acc3593d02e2a88fa17dd6d3c2abe"
name = "ella-checkout-functionality"
handle = "ella-checkout-functionality-1"
application_url = "https://airfare-tcp-actor-accomplished.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-for-customer-account-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://airfare-tcp-actor-accomplished.trycloudflare.com/auth/callback",
  "https://airfare-tcp-actor-accomplished.trycloudflare.com/auth/shopify/callback",
  "https://airfare-tcp-actor-accomplished.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
